// Static placeholder data only — no backend exists yet (see final report).
// Expanded so public discovery sections read as a real, active marketplace
// rather than a sparse prototype — same schema, more realistic volume/variety.
import { PropertyListing, ServiceListing } from "./types";

// Demo-only "saved" set, shared by /dashboard (Renting/Buying overview) and
// /dashboard/saved so both stay in sync rather than duplicating the list.
export const demoSavedListingIds = ["1", "3", "6", "5"];

export const mockListings: PropertyListing[] = [
  {
    id: "1",
    type: "rent",
    title: "2-Bedroom Flat, Lekki Phase 1",
    price: 1800000,
    currency: "NGN",
    state: "Lagos",
    lga: "Eti-Osa",
    bedrooms: 2,
    propertyType: "apartment",
    bathrooms: 2,
    furnishing: "semi-furnished",
    amenities: ["borehole", "power-backup", "parking", "gated-security"],
    rentDuration: "long-term",
    photoUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=70",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=70",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 214,
    description:
      "A bright, recently renovated 2-bedroom flat in a quiet, gated Lekki Phase 1 estate, close to shops and schools.",
  },
  {
    id: "2",
    type: "rent",
    title: "Studio Apartment, Yaba",
    price: 650000,
    currency: "NGN",
    state: "Lagos",
    lga: "Lagos Mainland",
    bedrooms: 1,
    propertyType: "studio",
    bathrooms: 1,
    furnishing: "furnished",
    amenities: ["borehole", "power-backup", "air-conditioning"],
    rentDuration: "short-term",
    photoUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=70",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 98,
    description:
      "Compact, fully furnished studio ideal for short stays, walking distance to the tech hub.",
  },
  {
    id: "3",
    type: "sale",
    title: "4-Bedroom Duplex, Abuja",
    price: 95000000,
    currency: "NGN",
    state: "Abuja (FCT)",
    lga: "Abuja Municipal Area Council",
    bedrooms: 4,
    propertyType: "duplex",
    bathrooms: 4,
    amenities: ["borehole", "power-backup", "gated-security", "parking", "fitted-kitchen", "balcony"],
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=70",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=70",
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 341,
    description:
      "A spacious family duplex with a private compound, generator house, and boys' quarters.",
  },
  {
    id: "4",
    type: "rent",
    title: "3-Bedroom Bungalow, Port Harcourt",
    price: 1200000,
    currency: "NGN",
    state: "Rivers",
    lga: "Port Harcourt",
    bedrooms: 3,
    propertyType: "bungalow",
    bathrooms: 2,
    furnishing: "unfurnished",
    amenities: ["borehole", "parking"],
    rentDuration: "long-term",
    photoUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=70"],
    verified: false,
    status: "live",
    viewCount: 47,
    description:
      "Newly built bungalow in a fast-developing residential area, close to the main expressway.",
  },
  {
    id: "5",
    type: "sale",
    title: "3-Bedroom Terrace, Ikeja GRA",
    price: 68000000,
    currency: "NGN",
    state: "Lagos",
    lga: "Ikeja",
    bedrooms: 3,
    propertyType: "terrace",
    bathrooms: 3,
    amenities: ["borehole", "power-backup", "gated-security", "parking", "fitted-kitchen"],
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=70",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 156,
    description:
      "Contemporary terrace home in the heart of Ikeja GRA, finished to a high standard with a private driveway.",
  },
  {
    id: "6",
    type: "rent",
    title: "1-Bedroom Serviced Apartment, Victoria Island",
    price: 2400000,
    currency: "NGN",
    state: "Lagos",
    lga: "Eti-Osa",
    bedrooms: 1,
    propertyType: "apartment",
    bathrooms: 1,
    furnishing: "furnished",
    amenities: ["power-backup", "air-conditioning", "gated-security", "fitted-kitchen"],
    rentDuration: "short-term",
    photoUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1200&q=70",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 302,
    description:
      "Fully serviced 1-bedroom apartment with 24/7 power and security, minutes from the business district.",
  },
  {
    id: "7",
    type: "sale",
    title: "5-Bedroom Detached House, Asokoro",
    price: 180000000,
    currency: "NGN",
    state: "Abuja (FCT)",
    lga: "Abuja Municipal Area Council",
    bedrooms: 5,
    propertyType: "detached",
    bathrooms: 5,
    amenities: ["borehole", "power-backup", "gated-security", "parking", "air-conditioning", "fitted-kitchen", "swimming-pool", "balcony"],
    photoUrl: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=70",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 89,
    description:
      "Executive 5-bedroom home in Asokoro with a swimming pool, staff quarters, and mature landscaped gardens.",
  },
  {
    id: "8",
    type: "rent",
    title: "2-Bedroom Terrace, Bodija",
    price: 900000,
    currency: "NGN",
    state: "Oyo",
    lga: "Ibadan North",
    bedrooms: 2,
    propertyType: "terrace",
    bathrooms: 2,
    furnishing: "unfurnished",
    amenities: ["borehole", "parking", "gated-security"],
    rentDuration: "long-term",
    photoUrl: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 63,
    description:
      "Quiet family-friendly terrace in Bodija, Ibadan, close to schools and the popular Bodija market.",
  },
  {
    id: "9",
    type: "sale",
    title: "4-Bedroom Semi-Detached, Independence Layout",
    price: 42000000,
    currency: "NGN",
    state: "Enugu",
    lga: "Enugu East",
    bedrooms: 4,
    propertyType: "detached",
    bathrooms: 3,
    amenities: ["borehole", "parking", "power-backup"],
    photoUrl: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 118,
    description:
      "Well-maintained semi-detached home in Independence Layout with a generous compound and boys' quarters.",
  },
  {
    id: "10",
    type: "rent",
    title: "2-Bedroom Apartment, Ikoyi",
    price: 3500000,
    currency: "NGN",
    state: "Lagos",
    lga: "Eti-Osa",
    bedrooms: 2,
    propertyType: "apartment",
    bathrooms: 2,
    furnishing: "furnished",
    amenities: ["power-backup", "air-conditioning", "gated-security", "parking", "fitted-kitchen", "balcony"],
    rentDuration: "long-term",
    photoUrl: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=70",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 275,
    description:
      "Elegant 2-bedroom apartment in a secure Ikoyi block with a gym, generator backup, and river views.",
  },
  {
    id: "11",
    type: "rent",
    title: "Self-Contain, GRA Phase 2",
    price: 380000,
    currency: "NGN",
    state: "Rivers",
    lga: "Port Harcourt",
    bedrooms: 1,
    propertyType: "studio",
    bathrooms: 1,
    furnishing: "unfurnished",
    amenities: ["borehole", "parking"],
    rentDuration: "short-term",
    photoUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 54,
    description:
      "Affordable, self-contained studio in GRA Phase 2, ideal for short stays close to the city centre.",
  },
  {
    id: "12",
    type: "sale",
    title: "3-Bedroom Bungalow, Nasarawa GRA",
    price: 35000000,
    currency: "NGN",
    state: "Kano",
    lga: "Nassarawa",
    bedrooms: 3,
    propertyType: "bungalow",
    bathrooms: 2,
    amenities: ["borehole", "parking"],
    photoUrl: "https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 72,
    description:
      "Spacious 3-bedroom bungalow on a quiet street in Nasarawa GRA, recently repainted with a large backyard.",
  },
  {
    id: "13",
    type: "sale",
    title: "5-Bedroom Waterfront Villa, Banana Island",
    price: 420000000,
    currency: "NGN",
    state: "Lagos",
    lga: "Eti-Osa",
    bedrooms: 5,
    propertyType: "detached",
    bathrooms: 6,
    amenities: ["borehole", "power-backup", "gated-security", "parking", "air-conditioning", "fitted-kitchen", "swimming-pool", "balcony"],
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=70",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 429,
    description:
      "An exceptional waterfront villa on Banana Island with a private jetty, home cinema, and staff quarters — Lagos's most exclusive address.",
  },
  {
    id: "14",
    type: "rent",
    title: "3-Bedroom Smart Apartment, Wuse 2",
    price: 4200000,
    currency: "NGN",
    state: "Abuja (FCT)",
    lga: "Abuja Municipal Area Council",
    bedrooms: 3,
    propertyType: "apartment",
    bathrooms: 3,
    furnishing: "furnished",
    amenities: ["power-backup", "air-conditioning", "gated-security", "parking", "fitted-kitchen", "balcony"],
    rentDuration: "long-term",
    photoUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 187,
    description:
      "Modern smart-home apartment in Wuse 2 with app-controlled lighting and security, walking distance to the central business district.",
  },
  {
    id: "15",
    type: "rent",
    title: "Studio Loft, Yaba Tech Hub",
    price: 950000,
    currency: "NGN",
    state: "Lagos",
    lga: "Lagos Mainland",
    bedrooms: 1,
    propertyType: "studio",
    bathrooms: 1,
    furnishing: "furnished",
    amenities: ["power-backup", "air-conditioning", "balcony"],
    rentDuration: "short-term",
    photoUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 133,
    description: "Bright, minimalist loft steps from Yaba's startup scene — fully furnished, fibre internet included.",
  },
  {
    id: "16",
    type: "sale",
    title: "4-Bedroom Courtyard House, Old GRA",
    price: 58000000,
    currency: "NGN",
    state: "Rivers",
    lga: "Port Harcourt",
    bedrooms: 4,
    propertyType: "detached",
    bathrooms: 4,
    amenities: ["borehole", "power-backup", "gated-security", "parking", "fitted-kitchen"],
    photoUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=70",
    galleryUrls: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=70"],
    verified: true,
    status: "live",
    viewCount: 96,
    description:
      "Character-filled courtyard house in Port Harcourt's Old GRA, with mature trees and a shaded veranda on every side.",
  },
  // -------------------------------------------------------------------------
  // SHARED PROPERTIES (added 31 Aug 2026)
  //
  // Rentals only, and the only two records in this file carrying
  // `occupancyType`/`shared` — the sixteen above are untouched and still parse
  // exactly as before, which is the point of the field being optional.
  //
  // `price` equals `shared.rentPerRoom` on both: what a renter pays for a
  // shared property is the room rent, so that is what the price filter, the
  // sort and the card should be reading.
  //
  // "18" is deliberately FULLY OCCUPIED. A shared listing with no rooms left
  // has to stay viewable while refusing new enquiries, and that state needs to
  // exist in the catalog or it never gets looked at.
  // -------------------------------------------------------------------------
  {
    id: "17",
    type: "rent",
    title: "Room in Shared 4-Bedroom Flat, Yaba",
    price: 700000,
    currency: "NGN",
    state: "Lagos",
    lga: "Lagos Mainland",
    bedrooms: 4,
    propertyType: "apartment",
    bathrooms: 2,
    furnishing: "semi-furnished",
    amenities: ["borehole", "power-backup", "parking", "fitted-kitchen"],
    rentDuration: "long-term",
    occupancyType: "shared",
    shared: {
      totalRooms: 4,
      bathroomType: "shared",
      kitchenShared: true,
      maxOccupantsPerRoom: 1,
      rentPerRoom: 700000,
      rooms: [
        { id: "17-r1", label: "Room 1", status: "occupied" },
        { id: "17-r2", label: "Room 2", status: "available" },
        { id: "17-r3", label: "Room 3", status: "available" },
        { id: "17-r4", label: "Room 4", status: "occupied" },
      ],
    },
    photoUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&q=70",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=70",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 143,
    description:
      "A room in a well-kept four-bedroom flat a short walk from the Yaba tech cluster. Housemates are working professionals; the kitchen and bathrooms are shared and cleaned on a rota.",
  },
  {
    id: "18",
    type: "rent",
    title: "Room in Shared 3-Bedroom Duplex, Wuse II",
    price: 950000,
    currency: "NGN",
    state: "Abuja (FCT)",
    lga: "Abuja Municipal Area Council",
    bedrooms: 3,
    propertyType: "duplex",
    bathrooms: 3,
    furnishing: "furnished",
    amenities: ["borehole", "power-backup", "gated-security", "parking", "air-conditioning"],
    rentDuration: "long-term",
    occupancyType: "shared",
    shared: {
      totalRooms: 3,
      bathroomType: "private",
      kitchenShared: true,
      maxOccupantsPerRoom: 2,
      rentPerRoom: 950000,
      rooms: [
        { id: "18-r1", label: "Room 1", status: "occupied" },
        { id: "18-r2", label: "Room 2", status: "occupied" },
        { id: "18-r3", label: "Room 3", status: "occupied" },
      ],
    },
    photoUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=70",
    galleryUrls: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=70",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=70",
    ],
    verified: true,
    status: "live",
    viewCount: 87,
    description:
      "En-suite rooms in a quiet, gated Wuse II duplex with full backup power. Each room has its own bathroom; the kitchen and living areas are shared between the three tenants.",
  },
];

// Categories match dashboard/service-listing's approved CATEGORIES list —
// no new categories introduced.
export const mockServices: ServiceListing[] = [
  {
    id: "s1",
    category: "Electrician",
    providerName: "Bright Spark Electrical",
    description: "Residential wiring, fault-finding, and generator installation across Lagos mainland.",
    state: "Lagos",
    lgas: ["Lagos Mainland", "Shomolu", "Surulere", "Ikeja"],
    verified: true,
    status: "live",
  },
  {
    id: "s2",
    category: "Plumber",
    providerName: "FlowFix Plumbing Services",
    description: "Leak repair, pipe installation, and bathroom fittings — same-day callouts.",
    state: "Lagos",
    lgas: ["Eti-Osa", "Ibeju-Lekki", "Lagos Island"],
    verified: true,
    status: "live",
  },
  {
    id: "s3",
    category: "Mechanic",
    providerName: "TorqueWorks Auto Care",
    description: "Mobile diagnostics, brake and engine repair for cars and light commercial vehicles.",
    state: "Rivers",
    lgas: [],
    verified: true,
    status: "live",
  },
  {
    id: "s4",
    category: "Carpenter",
    providerName: "Solidwood Furniture & Fittings",
    description: "Custom cabinetry, wardrobes, and door installation — free on-site measurement.",
    state: "Lagos",
    lgas: ["Ikeja", "Alimosho", "Kosofe", "Oshodi-Isolo", "Mushin"],
    verified: true,
    status: "live",
  },
  {
    id: "s5",
    category: "Painter",
    providerName: "ColourCraft Decorators",
    description: "Interior and exterior painting for homes and offices, with a 12-month workmanship guarantee.",
    state: "Abuja (FCT)",
    lgas: ["Abuja Municipal Area Council", "Bwari", "Kuje"],
    verified: true,
    status: "live",
  },
];
